# Conexi\u00F3n a Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-late-voice-auwtzwix-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_okjzwD2CP3WO
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00F3n Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false